app_bundle:
    resource: "@AppBundle/Controller"
    type:     annotation
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

api:
    type: rest
    resource: AppBundle\Controller\ApiController
    defaults: {_format: json}
    prefix: /api